### ISSUE TITLE
请问你这个东西怎么启动？

### ISSUE THREAD

**Issue by Helaiqu** [panyz/GankAndPanyz#1]
我将代码clone到本地，react-native run-android 无法启动。

**Comment by panyz** [comment]
@Helaiqu 这个项目是用了create-react-native-app来构建应用的，你可以参考下[《React Native高效开发》之reate-react-native-app](https://juejin.im/post/58d8ef5f44d9040069444989)这篇教程

**Comment by Helaiqu** [comment]
这个东西太不稳定，基本上连不上。

**Comment by panyz** [comment]
@Helaiqu 连不上？指的是什么啊？

**Comment by Helaiqu** [comment]
我说的是 Expo扫描生成二维码基本上链接不上。

**Comment by panyz** [comment]
@Helaiqu 你是在IDE上的终端去扫描的吗？或者你用电脑的终端去操作

**Comment by Helaiqu** [comment]
我是打开CMD进行npm start生成二维码，然后手机在同一网络状况下用Expo扫码，链接不上。就是这样，所以我说这个好像不靠谱。

**Comment by panyz** [comment]
@Helaiqu 喔，我自己试了下是可以的，电脑跟手机是在同一的WiFi下进行扫描的
